# Generated by Django 3.0.5 on 2021-03-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(choices=[('Benchmark.pl', 'Benchmark.pl'), ('boardgamesgeek.com', 'boardgamesgeek.com'), ('Tojuzbylo.pl', 'Tojuzbylo.pl'), ('Zwiadowca Historii', 'Zwiadowca Historii'), ('Computer World', 'Computer World'), ('InfoWorldPython.com', 'InfoWorldPython.com'), ('RealPython.com', 'RealPython.com'), ('bushcraftable.com', 'bushcraftable.com')], max_length=100)),
                ('title', models.CharField(max_length=256)),
                ('language', models.CharField(choices=[('PL', 'PL'), ('ENG', 'ENG')], max_length=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
