# Generated by Django 3.0.5 on 2021-02-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(choices=[('Benchmark.pl', 'Benchamark.pl'), ('Wykop.pl', 'Wykop.pl'), ('Tojuzbylo.pl', 'Tojuzbylo.pl'), ('Zwiadowca Historii', 'Zwiadowca Historii'), ('Computer World', 'Computer World')], max_length=100)),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(default='Author', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
